name: runTests

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  env:
    ESLINT_NO_DEV_ERRORS: true
  build:
    runs-on: windows-latest
    steps:
      - name: Create repository checkout
        uses: actions/checkout@v2

      - name: installing node
        uses: actions/setup-node@v2

      - name: installing newman
        run: npm install -g newman

      - name: installing eslint 
        run: npm install -g eslint

      - name: installing html reporter 
        run: npm install newman-reporter-htmlextra

      - name: running eslint
        run: eslint . --ext .js

      - name: Make directory to upload the test results
        run: mkdir -p testResults

      - name: running html reporter for newman
        run: newman run api/todoist.json --env-var token=${{secrets.TOKEN}} -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme  > testResults/runreport1.html

      - name: upload html reporter outputs
        uses: actions/upload-artifact@v2
        with: 
          name: RunReports
          path: testResults